module.exports = {
    purge: ['./containers/**/*.tsx', './components/**/*.tsx', './pages/**/*.tsx'],
    theme: {
      extend: {},
      fontFamily: {
        sans: [
          '"Noto Sans"',
          '"Noto Sans JP"',
          '"Noto Sans KR"',
          '"Noto Sans CJK JP"',
          '"Noto Sans CJK KR"',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          '"Segoe UI"',
          'Roboto',
          '"Helvetica Neue"',
          'Arial',
          '"Noto Sans"',
          'sans-serif',
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
        serif: ['Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
        mono: [
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          '"Courier New"',
          'monospace',
        ],
      },
      fontWeight: {
        300: 300,
        400: 400,
        600: 600,
        700: 700,
      },
      fontSize: {
        xs: '0.75rem',
        sm: '0.875rem',
        base: '1rem',
        lg: '1.125rem',
        xl: '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.775rem',
        '4xl': '2.25rem',
        '5xl': '2.75rem',
        '6xl': '4rem',
      },
      colors: {
        transparent: 'transparent',
        current: 'currentColor',
  
        black: '#000',
        white: '#fff',
  
        grey: {
          100: '#f7fafc',
          200: '#edf2f7',
          300: '#e2e8f0',
          400: '#cbd5e0',
          500: '#a0aec0',
          600: '#718096',
          700: '#4a5568',
          800: '#2d3748',
          900: '#1a202c',
        },
        dgrey: {
          100: '#4a5568',
          200: '#434d5e',
          300: '#3b4453',
          400: '#343b49',
          500: '#2c333e',
          600: '#252b34',
          700: '#1e222a',
          800: '#16191f',
          900: '#0f1115',
        },
        red: {
          lightest: '#f8d4d4',
          light: '#e25353',
          DEFAULT: '#db2828',
          dark: '#c52424',
        },
        orange: {
          lightest: '#ffdbb4',
          light: '#ffaa51',
          DEFAULT: '#ff8606',
          dark: '#e67905',
        },
        yellow: {
          lightest: '#feecb6',
          light: '#fedf85',
          DEFAULT: '#fcbe0a',
          dark: '#b08507',
        },
        green: {
          lightest: '#d3f1da',
          light: '#21ba45',
          DEFAULT: '#1a9537',
          dark: '#147029',
        },
        blue: {
          lightest: '#e6f2ff',
          light: '#3395ff',
          DEFAULT: '#007bff',
          dark: '#0056b3',
        },
        purple: {
          light: '#437ae1',
          DEFAULT: '#3e73db',
          darkish: '#1A47B5',
          dark: '#0649b6',
        },
        pink: {
          lightest: '#FCE7F3',
          light: '#F472B6',
          DEFAULT: '#EC4899',
          dark: '#DB2777',
        },
      },
      screens: {
        sm: '640px',
        md: '768px',
        lg: '1024px',
        xl: '1140px',
      },
      zIndex: {
        auto: 'auto',
        '-10': '-10',
        0: '0',
        10: '10',
        20: '20',
        30: '30',
        40: '40',
        50: '50',
      },
    },
    variants: {
      extend: {
        margin: ['first'],
        transitionProperty: ['hover', 'focus'],
        borderRadius: ['first', 'last'],
      },
    },
    darkMode: 'class',
  plugins: [],
}
